import {
  db,
  incidentsTable,
  safetyZonesTable,
  fogZonesTable,
  trafficStagnationTable,
  hospitalsTable,
  alertsTable,
} from "@workspace/db";

async function main() {
  console.log("Seeding RapidAid database...");

  // Reset
  await db.delete(incidentsTable);
  await db.delete(safetyZonesTable);
  await db.delete(fogZonesTable);
  await db.delete(trafficStagnationTable);
  await db.delete(hospitalsTable);
  await db.delete(alertsTable);

  // Bengaluru center
  const C = { lat: 12.9716, lng: 77.5946 };

  // Hospitals
  await db.insert(hospitalsTable).values([
    {
      name: "Manipal Hospital - HAL",
      type: "hospital",
      lat: 12.9569,
      lng: 77.6491,
      capacity: 18,
      status: "available",
      phone: "+91 80 2502 4444",
      address: "98, HAL Old Airport Road",
      responseTimeMins: 7,
    },
    {
      name: "Apollo Hospital Bannerghatta",
      type: "hospital",
      lat: 12.8956,
      lng: 77.5972,
      capacity: 24,
      status: "available",
      phone: "+91 80 2630 4050",
      address: "154/11 Bannerghatta Rd",
      responseTimeMins: 9,
    },
    {
      name: "Fortis Hospital Cunningham",
      type: "hospital",
      lat: 12.9854,
      lng: 77.5933,
      capacity: 12,
      status: "responding",
      phone: "+91 80 6621 4444",
      address: "14, Cunningham Rd",
      lastNotifiedAt: new Date(Date.now() - 1000 * 60 * 12),
      responseTimeMins: 5,
    },
    {
      name: "Narayana Multispeciality Mysore Rd",
      type: "hospital",
      lat: 12.9412,
      lng: 77.5346,
      capacity: 9,
      status: "available",
      phone: "+91 80 7122 2222",
      address: "Mysore Road",
      responseTimeMins: 11,
    },
    {
      name: "St. John's Medical College",
      type: "hospital",
      lat: 12.9279,
      lng: 77.6189,
      capacity: 30,
      status: "available",
      phone: "+91 80 2206 5000",
      address: "Sarjapur Rd, Koramangala",
      responseTimeMins: 8,
    },
    {
      name: "Cubbon Park Fire Station",
      type: "fire_station",
      lat: 12.9763,
      lng: 77.5929,
      capacity: 4,
      status: "available",
      phone: "101",
      address: "Cubbon Park",
      responseTimeMins: 6,
    },
    {
      name: "Indiranagar Police Station",
      type: "police",
      lat: 12.9719,
      lng: 77.6412,
      capacity: 12,
      status: "available",
      phone: "100",
      address: "100 Feet Rd, Indiranagar",
      responseTimeMins: 4,
    },
    {
      name: "108 Ambulance Hub - MG Road",
      type: "ambulance",
      lat: 12.9756,
      lng: 77.6097,
      capacity: 6,
      status: "available",
      phone: "108",
      address: "MG Road",
      responseTimeMins: 3,
    },
  ]);

  // Safety zones (women safety scoring per neighborhood / road segment)
  await db.insert(safetyZonesTable).values([
    {
      roadName: "MG Road",
      score: 82,
      lat: 12.9756,
      lng: 77.6097,
      radius: 600,
      factors: ["High pedestrian traffic", "Well-lit", "Police patrol"],
      timeOfDayRisk: "all",
      incidentCount: 2,
    },
    {
      roadName: "Indiranagar 100 Ft Rd",
      score: 76,
      lat: 12.9719,
      lng: 77.6412,
      radius: 700,
      factors: ["Active nightlife", "CCTV coverage"],
      timeOfDayRisk: "night",
      incidentCount: 4,
    },
    {
      roadName: "Koramangala 5th Block",
      score: 70,
      lat: 12.9352,
      lng: 77.6245,
      radius: 800,
      factors: ["Late-night activity", "Mixed lighting"],
      timeOfDayRisk: "dusk",
      incidentCount: 6,
    },
    {
      roadName: "Whitefield ITPL",
      score: 64,
      lat: 12.9698,
      lng: 77.7499,
      radius: 900,
      factors: ["Long stretches without lights", "Sparse foot traffic late night"],
      timeOfDayRisk: "night",
      incidentCount: 9,
    },
    {
      roadName: "Electronic City Phase 1",
      score: 58,
      lat: 12.8452,
      lng: 77.6602,
      radius: 1000,
      factors: ["Industrial corridor", "Limited public transport at night"],
      timeOfDayRisk: "night",
      incidentCount: 11,
    },
    {
      roadName: "Mysore Road underpass",
      score: 38,
      lat: 12.9412,
      lng: 77.5346,
      radius: 500,
      factors: ["Poor lighting", "Past harassment reports", "Few CCTV cameras"],
      timeOfDayRisk: "night",
      incidentCount: 17,
    },
    {
      roadName: "Yeshwanthpur industrial belt",
      score: 42,
      lat: 13.0287,
      lng: 77.5394,
      radius: 700,
      factors: ["Trucking corridor", "Sparse pedestrians", "Low lighting"],
      timeOfDayRisk: "night",
      incidentCount: 13,
    },
    {
      roadName: "JP Nagar 6th Phase",
      score: 74,
      lat: 12.9069,
      lng: 77.5854,
      radius: 600,
      factors: ["Residential", "Active RWA patrol"],
      timeOfDayRisk: "all",
      incidentCount: 3,
    },
    {
      roadName: "HSR Layout Sector 2",
      score: 80,
      lat: 12.9116,
      lng: 77.6412,
      radius: 500,
      factors: ["High visibility", "Cafés open late", "Patrolled"],
      timeOfDayRisk: "all",
      incidentCount: 1,
    },
    {
      roadName: "Banaswadi Outer Ring Road",
      score: 49,
      lat: 13.0162,
      lng: 77.6470,
      radius: 850,
      factors: ["Highway speeds", "Dim service road", "Past snatching reports"],
      timeOfDayRisk: "night",
      incidentCount: 10,
    },
    {
      roadName: "Cubbon Park perimeter",
      score: 71,
      lat: 12.9763,
      lng: 77.5929,
      radius: 500,
      factors: ["Public space", "Closes after 8pm"],
      timeOfDayRisk: "night",
      incidentCount: 4,
    },
    {
      roadName: "Marathahalli Bridge",
      score: 55,
      lat: 12.9591,
      lng: 77.6974,
      radius: 700,
      factors: ["Heavy traffic", "Limited footpath", "Crowded"],
      timeOfDayRisk: "dusk",
      incidentCount: 8,
    },
  ]);

  // Fog zones
  await db.insert(fogZonesTable).values([
    {
      lat: 12.8452,
      lng: 77.6602,
      radius: 1500,
      visibilityMeters: 80,
      severity: "dense",
      roadName: "Hosur Rd / Electronic City flyover",
      detectedAt: new Date(Date.now() - 1000 * 60 * 18),
    },
    {
      lat: 13.1986,
      lng: 77.7066,
      radius: 2400,
      visibilityMeters: 40,
      severity: "hazardous",
      roadName: "Bengaluru Airport approach",
      detectedAt: new Date(Date.now() - 1000 * 60 * 32),
    },
    {
      lat: 12.9069,
      lng: 77.5854,
      radius: 900,
      visibilityMeters: 220,
      severity: "moderate",
      roadName: "JP Nagar Outer Ring Rd",
      detectedAt: new Date(Date.now() - 1000 * 60 * 7),
    },
    {
      lat: 12.9591,
      lng: 77.6974,
      radius: 1200,
      visibilityMeters: 350,
      severity: "light",
      roadName: "Marathahalli — Outer Ring Rd",
      detectedAt: new Date(Date.now() - 1000 * 60 * 4),
    },
  ]);

  // Traffic stagnation (possible accidents detected from live pings)
  await db.insert(trafficStagnationTable).values([
    {
      lat: 12.9591,
      lng: 77.6974,
      radius: 350,
      stagnantMinutes: 24,
      vehicleCount: 47,
      suspicionScore: 88,
      roadName: "Marathahalli Bridge eastbound",
      detectedAt: new Date(Date.now() - 1000 * 60 * 24),
    },
    {
      lat: 12.9352,
      lng: 77.6245,
      radius: 220,
      stagnantMinutes: 14,
      vehicleCount: 22,
      suspicionScore: 62,
      roadName: "Sony Signal, Koramangala",
      detectedAt: new Date(Date.now() - 1000 * 60 * 14),
    },
    {
      lat: 12.9854,
      lng: 77.5933,
      radius: 180,
      stagnantMinutes: 9,
      vehicleCount: 15,
      suspicionScore: 41,
      roadName: "Cunningham Rd",
      detectedAt: new Date(Date.now() - 1000 * 60 * 9),
    },
  ]);

  // Incidents
  await db.insert(incidentsTable).values([
    {
      type: "accident",
      severity: "critical",
      status: "active",
      lat: 12.9591,
      lng: 77.6974,
      title: "Multi-vehicle collision on Marathahalli Bridge",
      description:
        "Three vehicles involved, eastbound lane completely blocked. Reports of injuries.",
      address: "Marathahalli Bridge, eastbound",
      reporter: "Citizen ping cluster",
      reportCount: 12,
    },
    {
      type: "harassment",
      severity: "high",
      status: "verified",
      lat: 12.9412,
      lng: 77.5346,
      title: "Group harassment near Mysore Rd underpass",
      description:
        "Multiple women reported being followed near the underpass between 9–10pm.",
      address: "Mysore Rd underpass",
      reporter: "Anonymous",
      reportCount: 4,
      createdAt: new Date(Date.now() - 1000 * 60 * 90),
    },
    {
      type: "fog",
      severity: "high",
      status: "active",
      lat: 13.1986,
      lng: 77.7066,
      title: "Hazardous fog on airport approach",
      description: "Visibility dropped below 50m. Multiple near-misses reported.",
      address: "Bengaluru International Airport approach",
      reporter: "Highway patrol",
      reportCount: 6,
    },
    {
      type: "medical",
      severity: "high",
      status: "active",
      lat: 12.9719,
      lng: 77.6412,
      title: "Cardiac emergency on 100 Ft Rd",
      description: "Person collapsed outside café. Bystanders performing CPR.",
      address: "Indiranagar 100 Ft Rd",
      reporter: "Bystander",
      reportCount: 2,
      createdAt: new Date(Date.now() - 1000 * 60 * 6),
    },
    {
      type: "fire",
      severity: "medium",
      status: "verified",
      lat: 13.0287,
      lng: 77.5394,
      title: "Industrial smoke reported",
      description: "Black smoke from a small workshop. No injuries reported yet.",
      address: "Yeshwanthpur industrial belt",
      reporter: "RWA member",
      reportCount: 3,
      createdAt: new Date(Date.now() - 1000 * 60 * 40),
    },
    {
      type: "suspicious",
      severity: "medium",
      status: "active",
      lat: 13.0162,
      lng: 77.6470,
      title: "Suspicious group on Banaswadi service road",
      description: "Several people loitering near parked vehicles after midnight.",
      address: "Banaswadi Outer Ring Rd",
      reporter: "Auto driver",
      reportCount: 2,
      createdAt: new Date(Date.now() - 1000 * 60 * 70),
    },
    {
      type: "traffic",
      severity: "low",
      status: "active",
      lat: 12.9352,
      lng: 77.6245,
      title: "Heavy congestion at Sony Signal",
      description: "Stalled signal and rain causing pile-up.",
      address: "Sony Signal, Koramangala",
      reporter: "Traffic cam",
      reportCount: 5,
      createdAt: new Date(Date.now() - 1000 * 60 * 14),
    },
    {
      type: "accident",
      severity: "medium",
      status: "resolved",
      lat: 12.9698,
      lng: 77.7499,
      title: "Two-wheeler skidded near ITPL",
      description: "Rider shifted to nearby clinic. Road cleared.",
      address: "ITPL Main Rd, Whitefield",
      reporter: "Citizen",
      reportCount: 1,
      createdAt: new Date(Date.now() - 1000 * 60 * 240),
      updatedAt: new Date(Date.now() - 1000 * 60 * 120),
    },
  ]);

  // Active alerts
  await db.insert(alertsTable).values([
    {
      severity: "critical",
      title: "Major accident — Marathahalli Bridge",
      message:
        "Multi-vehicle collision blocking eastbound lane. Avoid the bridge for the next 30 minutes.",
      category: "incident",
      lat: 12.9591,
      lng: 77.6974,
      radius: 1200,
      active: true,
      expiresAt: new Date(Date.now() + 1000 * 60 * 45),
      affectedUsers: 184,
    },
    {
      severity: "danger",
      title: "Hazardous fog near airport",
      message: "Visibility under 50m on the airport approach. Use low beams and reduce speed.",
      category: "fog",
      lat: 13.1986,
      lng: 77.7066,
      radius: 3000,
      active: true,
      expiresAt: new Date(Date.now() + 1000 * 60 * 90),
      affectedUsers: 92,
    },
    {
      severity: "warning",
      title: "Avoid Mysore Rd underpass at night",
      message:
        "Multiple harassment reports in the last week. Police patrols increased — consider an alternate route after 8pm.",
      category: "safety",
      lat: 12.9412,
      lng: 77.5346,
      radius: 800,
      active: true,
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 6),
      affectedUsers: 56,
    },
    {
      severity: "info",
      title: "Cubbon Park closing for maintenance",
      message: "South gate will be closed Sat 10pm – Sun 6am for tree pruning.",
      category: "system",
      lat: 12.9763,
      lng: 77.5929,
      radius: 600,
      active: true,
      expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 12),
      affectedUsers: 22,
    },
  ]);

  console.log("Seed complete.");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
